### ISSUE TITLE
Can logger to STDOUT be disabled when running tests

### ISSUE THREAD

**Issue by booyaa** [madetech/sensible_logging#25]
Can't reproduce locally on our own tests, but can be seen in the following repos:

- https://github.com/alphagov/govwifi-user-signup-api
- https://github.com/alphagov/govwifi-authentication-api
- https://github.com/alphagov/govwifi-logging-api

**Comment by cybojenix** [comment]
Given that this is normal behaviour for `Logger` too, I'm closing this as this is something to be done in the user's `spec_helper`
